
services:
  ai_app:
    build:
      context: ./
      dockerfile: ai_app/Dockerfile
    container_name: ai_app-container
    working_dir: /ai_app
    volumes:
      - ./:/ai_app
    ports:
      - "8011:8011"
    runtime: nvidia  # Использование GPU runtime
    environment:
      - NVIDIA_VISIBLE_DEVICES=all  # Указываем все доступные GPU
